package com.charactergeneratorgroup.charactergenerator.model.Enums;

public enum Advantage {

    BUENBEBEDOR("Buen bebedor",1,"El alcohol nunca te afecta negativamente, no importa cuánto bebas."),
    ESTOMAGODEHIERRO("Estómago de hierro",1, "La comida estropeada o cruda nunca te afecta negativamente y sigues consiguiendo el sustento necesario de ella."),
    EXTRANJERO("Extranjero",1, "Elige una nación de Théah que no sea tu tierra natal; ahí será donde te criaste. Por ejemplo, si tus padres eran castellanos pero te criaste en Vodacce, podrías ser Extranjero (Vodacce). Cualquier Riesgo que realices que se beneficiaría de una herencia doble (como usar Convencer para negociar entre dos mercaderes originarios de tus dos culturas o usar Tentar para saber qué decir para sobornar a una patrulla fronteriza y que te deje pasar sin inspeccionarte) consigue 1 dado adicional."),
    GRANDE("Grande",1, "No puedes adquirir la ventaja 'Pequeño'. Consigues 1 dado adicional en cualquier Riesgo que se vea beneficiado debido a tu tamaño, como por ejemplo, usar Atletismo para correr a toda velocidad mientras llevas a cuestas a otro héroe o acercarte a alguien para achantarlo con Intimidar."),
    LINGUISTA("Lingüista",1, "Hablas, lees y escribes todas las lenguas de Théah, incluso las muertas."),
    NOCIONDELTIEMPO("Noción del tiempo",1, "Siempre sabes qué hora es. Sabes cuánto falta hasta el siguiente amanecer o puesta de sol con menos de un minuto de margen de error."),
    PEQUENO("Pequeño",1, "No puedes adquirir la ventaja 'Grande'. Eres más pequeño que el resto de théanos medios. Mucho más pequeño. Consigues 1 dado adicional si tu tamaño hace que un Riesgo sea más fácil (como usar Esconder para escabullirte en un espacio pequeño y escapar de una patrulla de guardias o usar Atletismo para deslizarte entre los barrotes de una celda)."),
    SENTIDODELAORIENTACION("Sentido de la orientación",1, "Nunca te pierdes mientras tengas un punto de referencia, aunque eso no es lo mismo que saber exactamente dónde estás. Si te dejan inconsciente y te despiertas en una mazmorra, no tienes por qué saber en qué ciudad estás, pero si consigues escapar de la celda nunca te desviarás en los serpenteantes túneles de la mazmorra."),
    SUPERVIVIENTE("Superviviente",1, "Si te encuentras en la naturaleza, puedes forrajear o cazar y encontrar comida suficiente para ti y otras cinco personas. Bajo circunstancias extremas (perdido en medio de un desierto o abandonado en la tundra ussura, por ejemplo), encuentras comida suficiente para ti y otras dos personas."),
    UNOCONELBARCO("Uno con el barco",1, "Nunca pierdes el equilibrio mientras te encuentres a bordo de un barco. Además, consigues 1 dado adicional en cualquier Riesgo físico mientras estés a bordo de un barco en el mar (como enzarzarte en una lucha con espadas en la cubierta de un barco inclinado o escalar por el cordaje durante una tormenta)."),
    ALLANAMIENTODEMORADA("Allanamiento de morada",2, "Puedes gastar 1 punto de héroe para localizar un modo de entrar en un edificio o en un área restringida. Puedes llevar contigo hasta un personaje, pero el resto tiene que encontrar su propio modo de entrar o esperar hasta que les abras un camino."),
    AMIGOSENLACORTE("Amigos en la corte",2, "Cuando estés en un baile, un banquete o un acto similar de la alta sociedad, gasta 1 punto de héroe para revelar que tienes un amigo cercano que también está presente."),
    CALLEJERO("Callejero",2, "Puedes gastar 1 punto de héroe para localizar a alguien que te arregle un asunto, un soplón, un contrabandista o una figura similar de los bajos fondos."),
    CASADOCONELMAR("Casado con el mar",2, "Tienes acceso a un barco. Si tus aliados y tú ya tenéis acceso a un barco, entonces este gana un Trasfondo adicional."),
    CHISTPORAQUI("Chist, por aquí",2, "Mientras no te detecten, puedes gastar 1 punto de héroe para atraer a un solo personaje hasta tu posición y noquearlo. Otros personajes que se encuentren en la misma área no se dan cuenta de tu presencia."),
    CONTACTOS("Contactos",2, "Tienes contactos que pueden darte información o ayudarte cuando lo necesites. Elije un tipo de contacto, como 'Bajos fondos de Freiburg', 'Guardia de la ciudad de Cinco Velas' o 'Cortesanos de la clase alta de Vodacce', por ejemplo."),
    DERROTATEMERARIA("Derrota temeraria",2, "Gasta 1 punto de héroe para derrotar de manera inmediata a una sola banda de matones, independientemente de su Fuerza, pero recibes 1 Herida Dramática."),
    EQUILIBRIOPERFECTO("Equilibrio perfecto",2, "Gasta 1 punto de héroe para moverte por una viga estrecha, saltar de un lugar a otro o realizar cualquier otra hazaña de perfecta agilidad y equilibrio."),
    ESPIRITUVALIENTE("Espíritu valiente",2, "Empiezas cada partida con 2 puntos de héroe, en lugar de 1."),
    FASCINAR("Fascinar",2, "Gasta 1 punto de héroe para llamar la atención de otro personaje, que solo estará atento a ti hasta el final de la escena o hasta que dejes de hablarle o prestarle atención, lo que suceda primero."),
    HECHICERIA("Hechicería",2, "Consigues la Hechicería de la línea sanguínea de tu nación. Si adquieres esta ventaja después de crear el héroe, solo puedes hacerlo con una historia de héroe."),
    INMUNIDADALVENENO("Inmunidad al veneno",2, "El veneno nunca te afecta, aparte de un ligero malestar. Si normalmente el veneno te mataría, solo te hará vomitar, pero no tiene otros efectos secundarios."),
    INSPIRARGENEROSIDAD("Inspirar generosidad",2, "Gasta 1 punto de héroe para convencer a otro personaje de que te dé un objeto que quieres sin ningún coste. Podría darte algo que ya tiene o intentar conseguírtelo por todos los medios, legales o ilegales, sea cual sea la forma más fácil para él de echarle el guante a lo que quieres."),
    LIBERARSE("Liberarse",2, "Gasta, 1 punto de héroe para liberar tus manos de unas esposas, desatarte la cuerda que te ata a una silla o liberarte a ti mismo de cualquier otra forma similar."),
    LIDERAZGO("Liderazgo",2, "Gasta 1 punto de héroe para inspirar a un grupo a que actúe. El grupo debe poder oírte, pero si pueden hacerlo y son neutrales o tienen una buena disposición, harán lo que les mandes mientras sea algo razonable."),
    LOTENGO("¡Lo tengo!",2, "Gasta 1 punto de héroe para abrir una cerradura, abrir una caja fuerte o desactivar una trampa de manera inmediata."),
    MANOSO("Mañoso",2, "Gasta 1 punto de héroe para reparar un objeto roto, apañar una pistola estropeada, parchear un barco que tiene una fuga o realizar milagros similares que hagan que el objeto funcione con normalidad durante el resto de la escena."),
    MIRARFIJAMENTE("Mirar fijamente",2, "Gasta 1 punto de héroe para intimidar a un personaje y que retire una amenaza, te deje entrar donde no deberías o que se quite de tu camino de cualquier otro modo."),
    PARIENTESLEJANOS("Parientes lejanos",2, "Gasta 1 punto de héroe para revelar que tienes un primo lejano que vive cerca y que puede ayudarte con materiales, información o refugio."),
    REGATEAR("Regatear",2, "Gasta 1 punto de héroe para convencer a alguien de que haga un trato contigo, que te haga un descuento razonable o que le asegure a alguien que te conoce que 'eres bueno en algo'."),
    REPUTACION("Reputación",2, "Determina cuál es tu reputación con un solo adjetivo ('Honorable', 'Vicioso', etcétera). Cuando uses tu reputación para sacar ventaja en los Riesgos sociales, consigues 1 dado adicional."),
    SONRISAENCANTADORA("Sonrisa encantadora",2, "Gasta 1 punto de héroe para evitar que otro personaje saque un arma, empiece una pelea o recurra a la violencia."),
    TRABAJOENEQUIPO("Trabajo en equipo",2, "Puedes gastar 2 Aumentos para crear una Oportunidad y activar la Oportunidad en beneficio de otro héroe voluntario, que no necesita gastar su propio Aumento."),
    VENAQUI("Ven aquí",2, "Gasta 1 punto de héroe para atraer a otro personaje a una habitación privada y marcharte después de dicha habitación sin él, con lo que lo sacas de la escena."),
    VISTADELINCE("Vista de lince", 2, "Puedes ver perfectamente hasta una distancia de un kilómetro y medio mientras tengas una línea de visión despejada. Si usas un catalejo incluso puedes distinguir detalles, como la inscripción de un anillo. Si realizas un Riesgo que se base principalmente en tu visión, consigues 1 dado adicional"),
    VOLUNTADINDOMITA("Voluntad indómita", 2, "Gasta 1 punto de héroe para resistirte automáticamente después de que otro personaje intente intimidarte, seducirte o provocarte."),
    BOXEADOR("Boxeador",3, "Ganas 1 dado adicional cuando realices un Riesgo de Pelear para dar un puñetazo, una patada, un cabezazo o para herir de cualquier otro modo a un personaje usando únicamente tu cuerpo."),
    CAMARADERIA("Camaradería",3, "Cuando gastes 1 punto de héroe para ayudar a un aliado, este gana 4 dados en lugar de 3."),
    DONDEPONGOELOJO("Donde pongo el ojo",3, "Consigues 1 dado adicional cuando realizas un Riesgo de Apuntar usando una pistola, un trabuco o un arma arrojadiza como un cuchillo o un hacha."),
    ENFOQUEDINAMICO("Enfoque dinámico",3, "Gasta 1 punto de héroe para cambiar tu Enfoque durante una secuencia de acción o una secuencia dramática."),
    ESGRIMISTA("Esgrimista",3, "Consigues 1 dado adicional cuando realizas un Riesgo de Armas usando un florete, una daga, un alfanje u otra arma similar."),
    FRANCOTIRADOR("Francotirador", 3,"Ganas 1 dado adicional cuando realices un Riesgo de Apuntar usando un mosquete de cañón largo, un arco largo o una ballesta."),
    GORILA("Gorila", 3,"Ganas 1 dado adicional cuando realices un Riesgo de Armas usando un claymore, zweihander, hacha de batalla, alabarda o cualquier otra arma similar de dos manos."),
    HURTO("Hurto",3, "Gasta 1 punto de héroe para hurtar algo de un bolsillo, robar un anillo que otro personaje lleva puesto o colocar un pequeño objeto en la mano de otro personaje sin que se dé cuenta."),
    JACKMALTIEMPO("Jack Mal Tiempo",3, "Tu héroe consigue una segunda historia; créala del mismo modo que el resto de historias de héroe y su progreso y recompensas se determinan de manera independiente. Puede escribir otra nueva cuando esta historia se complete."),
    MAESTROARTESANO("Maestro Artesano",3, "Elige un tipo de objeto (armas, armaduras, pinturas, etcétera). Cuando creas un objeto de este tipo, puedes aumentar el tiempo de creación para hacer un objeto de mayor calidad. Si usas materiales típicos y normales, esto no tiene ningún efecto adicional, aparte del cosmético: se nota que el objeto es mejor que los objetos similares e incluso puede llevar tu marca, con lo que consigues notoriedad por un buen trabajo, obtienes un mayor precio si lo vendes, etcétera. Pero si usas materiales exóticos (como forjar una espada usando metal de una estrella caída, por ejemplo), puedes crear un Objeto distintivo para ti o para otro héroe. El tiempo necesario para crear un Objeto distintivo, y si un material es o no lo suficientemente «especial» para reunir las condiciones, siempre queda a discreción del DJ."),
    MECENAS("Mecenas",3, "Tienes un mecenas, ya sea un individuo o una organización, que aprecia tu trabajo y te proporciona un trabajo fijo. Empiezas cada sesión con Riqueza 1. Puedes gastar 1 punto de héroe para pedirle un favor a tu mecenas. Este favor suele ser político o mercantil de algún modo: tu mecenas podría darte una carta de presentación, mover hilos para colarte en una fiesta exclusiva, etcétera. Tu mecenas te puede pedir favores o tener otras expectativas para ti, como que produzcas bienes o arte en su beneficio si eres un artista o que ayudes al populacho en su nombre si eres un caballero."),
    MIEMBRODELAORDEN("Miembro de la Orden",3, "Puedes esperar refugio, un lugar donde quedarte y comida caliente en cualquier iglesia. También tienes acceso a muchas de las bibliotecas de la Iglesia, pero no a todas. Finalmente, también consigues 2 dados para cualquier Riesgo social contra personajes que sean adeptos de tu fe."),
    NUMERARIO("Numerario",3, "Puedes esperar refugio, un lugar donde quedarte y comida caliente en cualquier universidad. También tienes acceso a muchas de las bibliotecas de la universidad simplemente con pedirlo. Finalmente, también consigues 2 dados para cualquier Riesgo social contra personajes que sean miembros de una institución de enseñanza superior o que respete tal nivel de educación."),
    OBJETODISTINTIVO("Objeto Distintivo",3, "Elige un objeto específico que sea importante para ti. Descríbelo, decide por qué es importante y puedes incluso darle un nombre. Siempre puedes gastar 1 punto de héroe para: (Opción 1) Hacer que tu Objeto distintivo aparezca en la siguiente escena si lo has perdido o te lo han robado.(Opción 2) Conseguir 2 dados adicionales en un Riesgo cuando uses tu Objeto distintivo.(Opción 3) Si usas tu Objeto distintivo para atacar a un enemigo puedes infligirle tantas Heridas como Aumentos gastes más tu mayor característica.(Opción 4) Evitar tantas Heridas como Aumentos gastes, más tu mayor característica, cuando uses el Objeto distintivo. (Para todas las opciones) Siempre debes describir cómo te ayuda tu Objeto distintivo y tiene que tener sentido que el objeto te dé bonificaciones de este modo, a discreción del DJ."),
    OPORTUNISTA("Oportunista",3, "Cuando otro héroe gaste un Aumento para crear una Oportunidad puedes gastar 1 punto de héroe para activarla inmediatamente para ti."),
    PELEADEBAR("Pelea de Bar",3, "Ganas 1 dado adicional cuando realices un Riesgo con Pelear para luchar usando una mesa al revés, un taburete, un tablón de madera o cualquier otra arma improvisada."),
    REFLEJOSRAPIDOS("Reflejos Rápidos",3, "Elige una habilidad. Siempre realizas las acciones como si tuvieras un Aumento adicional para gastar cuando uses esa habilidad. Por ejemplo, si un héroe tiene Reflejos Rápidos con Armas y saca 3 Aumentos, realiza su primera acción a los 4 Aumentos. Si gasta 1 Aumento para realizar una acción (y le quedan 2 Aumentos), su siguiente acción se realiza a los 3 Aumentos. Un héroe puede adquirir esta ventaja más de una vez; elige una habilidad diferente cada vez."),
    RICO("Rico",3, "Empiezas cada sesión con Riqueza 3."),
    UNINOCENTEMALENTENDIDO("Un Inocente Malentendido",3, "Gasta 1 punto de héroe para corregir, eliminar o cambiar algo que tú u otro héroe acabáis de decir y «reinterpretar» las palabras en un cumplido amable."),
    VIRTUOSO("Virtuoso",3, "Elige un tipo de interpretación específica, como cantar, tocar un instrumento concreto o bailar. Consigues 1 dado adicional cuando realizas un Riesgo de Interpretar usando dicho arte."),
    ACADEMIA("Academia",4, "Estudiaste estrategia, equitación y cómo ser un soldado en una de las muchas academias militares de Théah. Cuando realices un Riesgo usando Atletismo, Tácticas de Guerra o Equitación, todos tus dados consiguen un +1 a su valor."),
    ALQUIMISTA("Alquimista",4, "Gasta 1 punto de héroe para fabricar un elixir o una poción que proporcione un efecto inmediato. Usar el brebaje alquímico requiere 1 Aumento durante una secuencia de acción o una secuencia dramática. Aquí tienes algunos ejemplos de usos de brebajes alquímicos, pero puede haber otros. Si quieres crear el tuyo propio, consúltalo con tu DJ. Explosión: El preparado provoca una explosión de humo asfixiante y fuego, lo que crea una Oportunidad que tú y otros podéis usar para huir de la escena. Mejora: Ganas 1 nivel en 1 característica durante 1 ronda. Aceite resbaladizo: Cualquier cosa que se cubra con este preparado se vuelve muy escurridiza y casi imposible de sostener. Si se vierte sobre el suelo, cualquiera que camine o corra sobre la superficie se resbalará y caerá. Si se vierte sobre un muro, cualquiera que intente escalarlo también se resbalará y caerá."),
    CAMORRISTA("Camorrista",4, "Estás acostumbrado a que tus oponentes vengan en bandadas. Resta tu Brío a las Heridas recibidas cuando te enfrentes a una banda de matones; el resultado son las Heridas que recibes, hasta un mínimo de 1."),
    CARACTERISTICALEGENDARIA("Característica Legendaria",4, "Elige una característica. Cuando hagas una tirada en un Riesgo usando esa característica, aparta un dado de tu reserva antes de tirar. Ese dado siempre se considera como un 10. Si tus 10 explotan, tu dado por la Característica legendaria también explota."),
    COMPANERODECONFIANZA("Compañero de Confianza",4, "Tienes un pequeño grupo de individuos que te son fieles o un único aliado de confianza que caminaría sobre fuego por ti (un guardaespaldas, un caballo, etcétera). Si tus aliados te ayudan directamente en un Riesgo, consigues 1 dado adicional si describes específicamente cómo te ayudan. Si les envías a cumplir alguna misión y necesitan realizar un Riesgo (a discreción del DJ), tiran 5 dados. Estos compañeros pueden recibir 5 Heridas antes de quedar Indefensos y es más que probable que requieran tu ayuda para que los rescates."),
    DURODEMATAR("Duro de Matar",4, "Ya no te quedas Indefenso cuando tienes 4 Heridas Dramáticas. En cambio, cuando eso suceda, cualquier villano que realice un Riesgo contra ti consigue 3 dados adicionales (en lugar de 2). Además, consigues una hilera adicional de Heridas. Cuando recibas tu quinta Herida Dramática, te quedas Indefenso."),
    ESPECIALISTA("Especialista",4, "Cuando adquieras esta ventaja, elige una habilidad en la que tengas al menos nivel 3 para que se convierta en tu habilidad de especialista. Cuando realices un Riesgo usando cualquier otra habilidad durante una secuencia de acción o dramática, no tienes que pagar Aumentos adicionales para Improvisar con tu habilidad de especialista. Un héroe solo puede tener una única habilidad de especialista; adquirir esta ventaja de nuevo te permite elegir una nueva habilidad, pero pierdes la anterior."),
    LICEO("Liceo",4, "Estudiaste retórica y debate y refinaste tus dotes sociales en uno de los muchos liceos de Théah o escuelas de señoritas normalmente reservados para la élite social y noble. Cuando realices un Riesgo usando Convencer, Intimidar o Tentar, todos tus dados suman un +1 a su valor."),
    SEIDR("Seidr",4, "Has estudiado con un skald vestenio. Has aprendido cómo ver los Nombres de las cosas, cómo conocer el futuro según el baile de las llamas de una hoguera y cómo guiar las pasiones de la gente, ya sea para alabar a tus héroes o ridiculizar a tus enemigos. Gasta 1 punto de héroe y pronuncia un discurso sobre otro personaje, que gana 1 nivel de Reputación (como la ventaja del mismo nombre) de tu elección, aumenta una Reputación existente en 1 nivel o cambia su Reputación a otra diferente a tu elección (pero el nivel sigue siendo el mismo). Si cambias la Reputación existente de un personaje, cualquiera que use la nueva Reputación contra él consigue tantos dados adicionales como el nivel de esa Reputación. Gasta 1 punto de héroe para lanzar runas, dados o huesos. Cuando lo hagas, hazle al DJ una pregunta sencilla sobre el futuro. El DJ debe responder con honestidad, pero solo tiene que decir sí o no. Si el evento en cuestión puede cambiar debido a las acciones de otros, como si una persona morirá o no, entonces la respuesta dada representa el resultado que actualmente es más probable, pero por lo demás este poder nunca se equivoca. Gasta 1 punto de héroe cuando mires a otro humano mortal para saber el nombre de esa persona. Ningún disfraz puede esconder el nombre ante ti ni tampoco creerás ninguna mentira diseñada para ocultar el nombre. Siempre reconocerás a esa persona durante el resto de la escena, no importa lo que ella haga por cambiar."),
    TOQUEMILAGROSO("Toque Milagroso",4, "Quizás fue por estudiar con la Iglesia o con un chamán local, pero conoces las heridas y sabes cómo curarlas. Gasta 1 punto de héroe y 1 Aumento durante tu acción para curar a otro héroe, que recuperará 1 Herida Dramática. Debes poder tocar al héroe que vayas a curar."),
    UNIVERSIDAD("Universidad",4, "Fuiste a una de las universidades regladas de Théah y estás familiarizado con muchos campos académicos de estudio como las matemáticas, la arquitectura y la astronomía. Cuando realices un Riesgo usando Conocimiento, Empatía o Percepción, todos tus dados ganan un +1 a su valor."),
    ACADEMIADEESGRIMA("Academia de Esgrima",5, "Puedes elegir un estilo de Esgrima. Si adquieres esta ventaja otra vez, consigues un estilo de Esgrima adicional."),
    CHISPADEGENIALIDAD("Chispa de Genialidad",5, "Elige un campo específico de estudio académico (astronomía, matemáticas, arquitectura, historia, etcétera). Cuando hagas un Riesgo y recurras a tu campo de estudio especializado, gasta 1 punto de héroe para conseguir tantos Aumentos adicionales como tu Ingenio."),
    LAFUERZADEDIEZ("La Fuerza de Diez",5, "Cuando lleves a cabo una proeza de fuerza bruta (levantar el rastrillo de un castillo, mantener una puerta cerrada contra un ariete que empuja al otro lado, etcétera), gasta 1 punto de héroe para aumentar, en ese Riesgo, todos los valores de tus dados tanto como tu Músculo o Brío, lo que sea mayor. Por ejemplo, si estás intentando evitar que una pared en ruinas colapse para que tus amigos puedan escapar, gasta 1 punto de héroe para sumarle tu Músculo al número de cada uno de tus dados."),
    JOIEDEVIVRE("Joie de Vivre",5, "Justo antes de que tenga lugar una confrontación con un villano, gasta 1 punto de héroe y haz algún tipo de comentario breve o inteligente como: «El alma brilla más cuando las cosas parecen más oscuras». Todos los héroes que lo escuchen cuentan como 10 todos los dados que tiren en su siguiente tirada y tengan un valor igual o inferior a su habilidad."),
    JUNTOSSOMOSFUERTES("Juntos Somos Fuertes",5, "Gasta 1 punto de héroe para darle cualquiera de tus Aumentos a otro héroe que se encuentre en la misma escena, siempre y cuando te pueda ver o escuchar. Puedes darle todos los Aumentos que desees."),
    NOSOMOSTANDIFERENTES("No Somos Tan Diferentes...",5, "Gasta 1 punto de héroe para convencer a un villano de que estás de su lado, considerándote así un aliado de confianza. La ilusión se acaba en cuanto el villano te vea realizar una acción heroica o te niegues a realizar una acción de villanía. Solo puedes usar esta ventaja en cada villano una vez. «Si me engañas una vez…»."),
    NOVOYAMORIRAQUÍ("No Voy a Morir Aquí",5, "Gasta 1 punto de héroe para ignorar todos los efectos negativos de Heridas Dramáticas durante la ronda: el villano no consigue dados adicionales si tienes 2 Heridas Dramáticas y tú no te quedas Indefenso con 4 Heridas Dramáticas."),
    LASUERTEDIABLO("La Suerte del Diablo",5, "Gasta 1 punto de héroe después de realizar un Riesgo para volver a tirar tantos dados como quieras. Debes quedarte con la nueva tirada, a menos que tengas otro efecto que te permita volver a tirar los dados. Solo puedes utilizar esta ventaja una vez por escena."),
    TUTEVIENESCONMIGO("Tú te Viene Conmigo",5, "Gasta 1 punto de héroe para hacer que todo el daño que inflijas esta ronda aumente tanto como Heridas Dramáticas tengas.");


    private String advantageName;
    private Integer advantagePoints;
    private String advantageDescription;

    Advantage(String advantageName,Integer advantagePoints, String advantageDescription) {
        this.advantageName = advantageName;
        this.advantagePoints = advantagePoints;
        this.advantageDescription = advantageDescription;
    }

    public String getAdvantageName() {
        return advantageName;
    }

    public Integer getAdvantagePoints() {
        return advantagePoints;
    }

    public String getAdvantageDescription() {
        return advantageDescription;
    }


}
